plone/plone.app.querystring

CHANGES.rst
plone/app/querystring/profiles.zcml
plone/app/querystring/profiles/default/metadata.xml
plone/app/querystring/profiles/default/registry.xml
plone/app/querystring/profiles/upgrades/to_7/registry.xml
plone/app/querystring/upgrades.zcml

Any reason, why sorting by getObjPositionInParent has not been enabled by default?

Fix getObjPositionInParent be sortable

---

plone/app/querystring/profiles.zcml
plone/app/querystring/profiles/default/registry.xml
plone/app/querystring/profiles/upgrades/to_6/registry.xml
plone/app/querystring/queryparser.py
plone/app/querystring/upgrades.zcml

change Subject QueryField operators to use selection.oneOf and selection.all
operators. The change make's it possible to use "oneOf" (OR) and "all" (AND) for
Tag criteria of collections. Now is there only a meaningless "Is" operator.

Add operators selection.any and selection.all to Subject

---

CHANGES.rst
plone/app/querystring/indexmodifiers/query_index_modifiers.py
plone/app/querystring/profiles.zcml
plone/app/querystring/profiles/default/metadata.xml
plone/app/querystring/profiles/default/registry.xml
plone/app/querystring/profiles/upgrades/to_9/registry.xml
plone/app/querystring/queryparser.py
plone/app/querystring/tests/testQueryParser.py
plone/app/querystring/upgrades.zcml

This PR fixes 2 issues currently present with collections:
1) When choosing the "Between dates" operation, there is a first call with empty values that throws an error
2) When a collection has a date stored for a query, the index modifier left it as a string, causing the catalog query to not work properly. This converts the string to a proper datetime for searches.

Collections fixes

---

CHANGES.rst
plone/app/querystring/querybuilder.py

The preview results of a collection are not the same as the real one when the path is not set. This fixes it.

fix: set path to navigation root by default

---

CHANGES.rst
plone/app/querystring/configure.zcml
plone/app/querystring/interfaces.py
plone/app/querystring/querybuilder.py
plone/app/querystring/querymodifiers.py
setup.py

Refactor addition of criteria to stick inside ``INavigationRoot`` in querybuilder.
Added a simple ``IQueryModifier`` interfaces expecting a query and returning a query.
Iterates over all sorted utilities providing such an interfaces and calls it right before the query is parsed.
Code to add the ``INavigationRoot`` stickyness was moved to such a query modifier.

Introduce IQueryModifier, refactor INavigationRoot stickyness.

---

CHANGES.rst
plone/app/querystring/indexmodifiers/query_index_modifiers.py
plone/app/querystring/tests/testIndexmodifiers.py

Fix a case, where index modifiers with queries containing ``largerThanRelativeDate`` or ``lessThanRelativeDate`` date operators failed with an ``TypeError``.

RelativeDate index modifier fix

---

CHANGES.rst
plone/app/querystring/queryparser.py
plone/app/querystring/tests/testQueryParser.py

Fixes their usage via QueryStringFieldWidget.

Make integer query operators accept unicode values.

---

CHANGES.rst
plone/app/querystring/querybuilder.py
plone/app/querystring/tests/testQueryBuilder.py

To fullfill the API when a Batch object was expected. E.g. it broke with empty queries when trying to access batch.length

Fix QueryBuilder with empty queries to return a Batch when requested.

---

CHANGES.rst
plone/app/querystring/queryparser.py
plone/app/querystring/tests/testQueryParser.py

Otherwise you get a `CatalogError`.
This can happen when you are adding a Collection and there is no sort index selected yet. The javascript then queries for `sort_on=null`:
`http://127.0.0.1:8080/Plone/portal_factory/@@querybuilder_html_results?query.i:records=review_state&query.o:records=plone.app.querystring.operation.selection.is&query.v:records:list=published&sort_on=null`
This is on Plone 4.3, and might need plone.app.contenttypes. At least, I found this on a site with plone.app.contenttypes, and did not see it on a site with plone.app.collection, but maybe there is something specific for that site in play.
Sample traceback:
```
Traceback (innermost last):
Module ZPublisher.Publish, line 138, in publish
Module ZPublisher.mapply, line 77, in mapply
Module ZPublisher.Publish, line 48, …
```

Ignore unknown `sort_on` indexes when parsing a query. [1.2.x]

---

CHANGES.rst
plone/app/querystring/queryparser.py
plone/app/querystring/tests/testQueryParser.py

Otherwise you get a `CatalogError`.

Ignore unknown `sort_on` indexes when parsing a query. [master]

---

CHANGES.rst
plone/app/querystring/queryparser.py
plone/app/querystring/tests/testQueryParser.py

Otherwise you get a `CatalogError`.

Ignore unknown `sort_on` indexes when parsing a query. [1.3.x]

---

news/93.bugfix
plone/app/querystring/queryparser.py
plone/app/querystring/tests/testQueryParser.py

Most notably this did not happen for unicode on Python 2.
So a `u"42"` was passed as value to the catalog query, and this matched either all or nothing.
Fixes https://github.com/plone/plone.app.querystring/issues/93 for Plone 5.1 and 5.2.

Integer criterions: try to convert all input to integers.

---

news/93.bugfix
plone/app/querystring/queryparser.py
plone/app/querystring/tests/testQueryParser.py

Most notably this did not happen for unicode on Python 2.
So a `u"42"` was passed as value to the catalog query, and this matched either all or nothing.
Fixes https://github.com/plone/plone.app.querystring/issues/93 for Plone 4.3.
Note: I can think of various ways of handling a value that gives an exception (`int("bad value")`):
- Use zero as value.
- Use `None` as value.
- Return an empty dictionary as result.
- Do not catch the exception, but let it propagate: either the caller will handle it, or the end user gets a clear traceback.
I choose to catch all exceptions and use `None` as value, as this seems to be what is happening in the other queryparser functions that explicitly catch exceptions.

Integer criterions: try to convert all input to integers. [1.2.x]

---

news/97.bugfix
plone/app/querystring/queryparser.py

Issue #97 i.e. allow for MultiPath Queries

---

news/104.feature
plone/app/querystring/interfaces.py
plone/app/querystring/registryreader.py
plone/app/querystring/tests/registry_testdata.py

Huge vocabularies cause serious performance problems in the server
memory, in the network payload, and in the browser, because the large
result set is fetched pointlessly. An application can set lazy=True
for such vocabularies, and at the same time override the operations
from xml to provide an "autocomplete" widget. Such a widget does not
need any initial results but will search and fetch the vocabulary
lazily, on demand.
The use case targets Volto sites, but the problem is not specific to
Volto.

Add lazy attribute to vocabularies to prevent fetching any results

---

news/103.bugfix
plone/app/querystring/querybuilder.py
plone/app/querystring/tests/testQueryBuilder.py

For example when you perform a restapi call to filter by UID and the endpoint automatically add a not query for current context's UID.
With old code we used "update" method that overrides the vale of the query.

Fix query update with custom query

---

news/111.bugfix
plone/app/querystring/querybuilder.py
plone/app/querystring/tests/testQueryBuilder.py

I just copied over the function `munge_search_terms` from https://github.com/plone/Products.CMFPlone/pull/3518
We are using the same plone.app.querystring version for both Plone 5.2.x and 6, so it is not possible to import from Products.CMFPlone and neither from plone.base if that function is ever moved to there.
Opinions? @petschki @jensens @mauritsvanrees

Fixes #111 for branch 1.x

---

news/fix-circular-dep-pavocabularies.bugfix
plone/app/querystring/configure.zcml
plone/app/querystring/queryparser.py
plone/app/querystring/tests/testVocabularies.py
plone/app/querystring/vocabularies.py
setup.py

- New direct dependency explicit on `plone.app.vocabularies`.
- Move `plone.app.vocabularies.catalog.CatalogVocabularyFactory` to `.vocabularies`, move the ZCML to register the factory, move the the test.
- Move `plone.app.vocabularies.utils.parse_query` with new name `parseAndModifyFormquery` to `.queryparser`.
Has to be tested and merged together with https://github.com/plone/plone.app.vocabularies/pull/76
GHA test will fail.

Fix a circular dependency to plone.app.vocabularies

---

news/132.bugfix
plone/app/querystring/queryparser.py
plone/app/querystring/tests/testQueryParser.py

If one query operation performs a min range query and another performs a max range query on the same index, merge them together into a minmax. Fixes #130.
Note: depends on https://github.com/plone/plone.app.querystring/pull/131

Merge multiple range queries

---

news/135.bugfix
plone/app/querystring/queryparser.py
plone/app/querystring/tests/testQueryParser.py

Fix currentUser operation

---

news/137.feature
plone/app/querystring/registryreader.py
plone/app/querystring/tests/testRegistryReader.py

Add a way to get querystring info with vocabularies fetched in a specific context.
(This doesn't change anything on its own. I'm going to make a related PR in plone.restapi which uses it.)

Support getting querystring vocabs in context

---

news/139.bugfix
plone/app/querystring/querybuilder.py
plone/app/querystring/tests/testQueryBuilder.py

Fixes #139 
See also:
- https://github.com/plone/Products.CMFPlone/issues/3879
- https://github.com/plone/Products.CMFPlone/pull/3880
- https://github.com/plone/Products.CMFPlone/pull/3881 
I have also ported the tests for this functions because they were not ported when the code was copied-over.

handle parenthesis inside quotes
